name: Assign Triage label to new tickets and add to project board
on:
  issues:
    types: [opened]

jobs:
    label: Add Triage label abd add to project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-ecosystem/action-add-labels@v1
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      labels: triage

    - name: "Assign issues to project board"
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/orgs/microsoft/projects/48'
        column_name: 'Backlog'